version: 2.1
jobs:
  build:
    docker:
      - image: golang:latest
    working_directory: github.com/raynnenogueira/aula-ci
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test -v
